---------------------------BOND CIS 昨天------------------------------------
WITH WPH_LIST AS (
	SELECT WFR_QTY,
	CASE
	WHEN STEP_NAME='BO-B1-Bonding' THEN 'OP'
	WHEN STEP_NAME='BO-B2-Bonding' THEN 'B2'
	WHEN STEP_NAME='SPRC' THEN 'SPRC'
	WHEN DEVICE_ID LIKE 'OV023%' AND STEP_NAME='BO-Bo-Ca1-Bonding' THEN 'BCSM'
	WHEN DEVICE_ID LIKE 'OX02A%' AND STEP_NAME='BO-Bo-Ca1-Bonding' THEN 'BCSM'
	WHEN DEVICE_ID LIKE 'OX01A' AND STEP_NAME='BO-Bo-Ca1-Bonding' THEN 'BCSM'
	WHEN DEVICE_ID LIKE 'OV1065%' AND STEP_NAME='BO-Bo-Ca1-Bonding' THEN 'BCSM'
	WHEN DEVICE_ID LIKE 'OV1064%' AND STEP_NAME='BO-Bo-Ca1-Bonding' THEN 'BCSM'
	WHEN DEVICE_ID LIKE 'OV10626%' AND STEP_NAME='BO-Bo-Ca1-Bonding' THEN 'BCSM'
	WHEN DEVICE_ID LIKE 'OV07261%' AND STEP_NAME='BO-Bo-Ca1-Bonding' THEN 'BCSM'
	WHEN TECH_ID LIKE 'Cygnus%' AND TECH_ID LIKE '%TSV%' AND STEP_NAME='BO-B1-Bonder_Bonding' THEN 'TSV'
	WHEN TECH_ID LIKE 'CSP%' AND TECH_ID LIKE 'XinPac%' AND STEP_NAME='BO-B1-Bonder_Bonding' THEN 'CSP'
	WHEN TECH_ID LIKE 'Fort-B%' AND STEP_NAME='BO-Bo-Ca1-Bonding' THEN 'Fort-B'
	WHEN TECH_ID LIKE '%MEMS%' AND STEP_NAME='BO-Bo-Ca1-Bonding' THEN 'MEMS-B1'
	WHEN TECH_ID LIKE '%MEMS%' AND STEP_NAME='BO-Bo-Ca2-Bonding' THEN 'MEMS-B2'
    END DEVICE_ID
	FROM CIMDM.DM_MOVE_BT WHERE (STEP_NAME IN ('BO-B1-Bonding','BO-B2-Bonding','SPRC','BO-Bo-Ca1-Bonding','BO-B1-Bonder_Bonding','BO-Bo-Ca2-Bonding') AND EQP_ID LIKE 'BBOBO%')
	AND TRACK_OUT_BT BETWEEN TO_DATE(to_char(sysdate-1,'yyyy-mm-dd') || ' 07:30:00','yyy-mm-dd hh24:24:mi:ss')
	AND TO_DATE(to_char(sysdate,'yyyy-mm-dd') || ' 07:30:00','yyy-mm-dd hh24:24:mi:ss')
),
WPH_SUM_TOTAL AS (
	SELECT SUM(WFR_QTY) WFR_QTY FROM WPH_LIST
),
WPH_SUM AS (
	SELECT SUM(WFR_QTY) WFR_QTY,DEVICE_ID FROM WPH_LIST GROUP BY DEVICE_ID
),
WPH_TABLE AS (
	SELECT DEVICE_ID,CASE 
	WHEN DEVICE_ID='OP' THEN 16.20
	WHEN DEVICE_ID='B2' THEN 14.80
    WHEN DEVICE_ID='SPRC' THEN 1.5
	WHEN DEVICE_ID='BCSM' THEN 6.00
	WHEN DEVICE_ID='TSV' THEN 1.58
    WHEN DEVICE_ID='CSP' THEN 1.34
	WHEN DEVICE_ID='Fort-B' THEN 3.50
	WHEN DEVICE_ID='MEMS-B1' THEN 7.50
	WHEN DEVICE_ID='MEMS-B2' THEN 7.50
	END WPHTABLE FROM WPH_TABLE
),
WPH_TABLE_STD AS (
	SELECT MAX(WPHTABLE) MAX_STD FROM WPH_TABLE
),
WPH_TABLE2 AS (
	SELECT A.DEVICE_ID,B.MAX_STD/A.WPHTABLE WPHTABLE FROM WPH_TABLE A , WPH_TABLE_STD B
),
WPH_CALCULATE_F AS (
	SELECT A.DEVICE_ID,A.WFR_QTY*B.WPHTABLE R_RESULT FROM WPH_SUM A JOIN WPH_TABLE2 B ON A.DEVICE_ID=B.DEVICE_ID
),
WPH_CALCULATE_B AS (
	SELECT SUM(R_ESULT) R_ESULT FROM WPH_CALCULATE_F
),
UP_LIST AS (
	SELECT ROUND(AVG(UP),4) UP FROM CIMDM.RPT_KER_SUM WHERE EQP_ID LIKE 'BBOBO%'
	AND WIPDATE = TO_DATE(SYSDATE-1,'yyyy-mm-dd')
),
AVL_LIST AS (
	SELECT ROUND(AVG(UP+DOWN),4) UP FROM CIMDM.RPT_KER_SUM WHERE EQP_ID LIKE 'BBOBO%'
	AND WIPDATE = TO_DATE(SYSDATE-1,'yyyy-mm-dd')
)
SELECT ROUND(A.R_ESULT/((B.UP/100)*C.MAX_STD*26*24),4) EFF , ROUND(A.R_ESULT,2) TTL_TOTAL ,C.MAX_STD,D.WFR_QTY E1_MAIN_MOVE,
((B.UP/100)*C.MAX_STD*26*24) MOVE_TARGET,B.UP,E.UP FROM
WPH_CALCULATE_B A,UP_LIST B,WPH_TABLE_STD C,WPH_SUM_TOTAL D,AVL_LIST E

---------------------------E1 & E2 CIS 現在------------------------------------------------


WITH WPH_LIST AS (
	SELECT WFR_QTY,
	CASE
	WHEN STEP_NAME='BO-B1-Bonding' THEN 'OP'
	WHEN STEP_NAME='BO-B2-Bonding' THEN 'B2'
	WHEN STEP_NAME='SPRC' THEN 'SPRC'
	WHEN DEVICE_ID LIKE 'OV023%' AND STEP_NAME='BO-Bo-Ca1-Bonding' THEN 'BCSM'
	WHEN DEVICE_ID LIKE 'OX02A%' AND STEP_NAME='BO-Bo-Ca1-Bonding' THEN 'BCSM'
	WHEN DEVICE_ID LIKE 'OX01A' AND STEP_NAME='BO-Bo-Ca1-Bonding' THEN 'BCSM'
	WHEN DEVICE_ID LIKE 'OV1065%' AND STEP_NAME='BO-Bo-Ca1-Bonding' THEN 'BCSM'
	WHEN DEVICE_ID LIKE 'OV1064%' AND STEP_NAME='BO-Bo-Ca1-Bonding' THEN 'BCSM'
	WHEN DEVICE_ID LIKE 'OV10626%' AND STEP_NAME='BO-Bo-Ca1-Bonding' THEN 'BCSM'
	WHEN DEVICE_ID LIKE 'OV07261%' AND STEP_NAME='BO-Bo-Ca1-Bonding' THEN 'BCSM'
	WHEN TECH_ID LIKE 'Cygnus%' AND TECH_ID LIKE '%TSV%' AND STEP_NAME='BO-B1-Bonder_Bonding' THEN 'TSV'
	WHEN TECH_ID LIKE 'CSP%' AND TECH_ID LIKE 'XinPac%' AND STEP_NAME='BO-B1-Bonder_Bonding' THEN 'CSP'
	WHEN TECH_ID LIKE 'Fort-B%' AND STEP_NAME='BO-Bo-Ca1-Bonding' THEN 'Fort-B'
	WHEN TECH_ID LIKE '%MEMS%' AND STEP_NAME='BO-Bo-Ca1-Bonding' THEN 'MEMS-B1'
	WHEN TECH_ID LIKE '%MEMS%' AND STEP_NAME='BO-Bo-Ca2-Bonding' THEN 'MEMS-B2'
    END DEVICE_ID
	FROM CIMDM.DM_MOVE_BT WHERE (STEP_NAME IN ('BO-B1-Bonding','BO-B2-Bonding','SPRC','BO-Bo-Ca1-Bonding','BO-B1-Bonder_Bonding','BO-Bo-Ca2-Bonding') AND EQP_ID LIKE 'BBOBO%')
	AND TRACK_OUT_BT BETWEEN TO_DATE(to_char(sysdate,'yyyy-mm-dd') || ' 07:30:00','yyy-mm-dd hh24:24:mi:ss')
	AND TO_DATE(to_char(sysdate+1,'yyyy-mm-dd') || ' 07:30:00','yyy-mm-dd hh24:24:mi:ss')
),
WPH_SUM_TOTAL AS (
	SELECT SUM(WFR_QTY) WFR_QTY FROM WPH_LIST
),
WPH_SUM AS (
	SELECT SUM(WFR_QTY) WFR_QTY,DEVICE_ID FROM WPH_LIST GROUP BY DEVICE_ID
),
WPH_TABLE AS (
	SELECT DEVICE_ID,CASE 
	WHEN DEVICE_ID='OP' THEN 16.20
	WHEN DEVICE_ID='B2' THEN 14.80
    WHEN DEVICE_ID='SPRC' THEN 1.5
	WHEN DEVICE_ID='BCSM' THEN 6.00
	WHEN DEVICE_ID='TSV' THEN 1.58
    WHEN DEVICE_ID='CSP' THEN 1.34
	WHEN DEVICE_ID='Fort-B' THEN 3.50
	WHEN DEVICE_ID='MEMS-B1' THEN 7.50
	WHEN DEVICE_ID='MEMS-B2' THEN 7.50
	END WPHTABLE FROM WPH_TABLE
),
WPH_TABLE_STD AS (
	SELECT MAX(WPHTABLE) MAX_STD FROM WPH_TABLE
),
WPH_TABLE2 AS (
	SELECT A.DEVICE_ID,B.MAX_STD/A.WPHTABLE WPHTABLE FROM WPH_TABLE A , WPH_TABLE_STD B
),
WPH_CALCULATE_F AS (
	SELECT A.DEVICE_ID,A.WFR_QTY*B.WPHTABLE R_RESULT FROM WPH_SUM A JOIN WPH_TABLE2 B ON A.DEVICE_ID=B.DEVICE_ID
),
WPH_CALCULATE_B AS (
	SELECT SUM(R_ESULT) R_ESULT FROM WPH_CALCULATE_F
),
UP_LIST AS (
	SELECT ROUND(AVG(UP),4) UP FROM CIMDM.RPT_KER_SUM WHERE EQP_ID LIKE 'BBOBO%'
	AND WIPDATE = TO_DATE(SYSDATE,'yyyy-mm-dd')
),
AVL_LIST AS (
	SELECT ROUND(AVG(UP+DOWN),4) UP FROM CIMDM.RPT_KER_SUM WHERE EQP_ID LIKE 'BBOBO%'
	AND WIPDATE = TO_DATE(SYSDATE,'yyyy-mm-dd')
)
SELECT ROUND(A.R_ESULT/((B.UP/100)*C.MAX_STD*26*ROUND((SYSDATE - TO_DATE(TO_CHAR(SYSDATE, 'YYYY-MM-DD') || ' 07:30:00', 'YYYY-MM-DD HH24:MI:SS')) * 24, 4)),4) EFF , ROUND(A.R_ESULT,2) TTL_TOTAL ,C.MAX_STD,D.WFR_QTY E1_MAIN_MOVE,
((B.UP/100)*C.MAX_STD*26*ROUND((SYSDATE - TO_DATE(TO_CHAR(SYSDATE, 'YYYY-MM-DD') || ' 07:30:00', 'YYYY-MM-DD HH24:MI:SS')) * 24, 4)) MOVE_TARGET,
B.UP,E.UP FROM
WPH_CALCULATE_B A,UP_LIST B,WPH_TABLE_STD C,WPH_SUM_TOTAL D,AVL_LIST E