---------------------------superE 昨天------------------------------------
WITH WPH_LIST AS (
	SELECT WFR_QTY,
	CASE
	WHEN EQP_ID LIKE 'BETSE%' AND LOT_TYPE='MD' THEN 'MD'
	WHEN EQP_ID LIKE 'BETSE%' AND STEP_NAME LIKE 'ET-OO-Etching' THEN 'OO'
	WHEN EQP_ID LIKE 'BETSE%' AND STEP_NAME LIKE 'ET-ViaE-Oxide_Etch-ME' THEN 'ViaE'
	WHEN EQP_ID LIKE 'BETSE%' AND STEP_NAME LIKE 'ET-LL-Ar_Clean' THEN 'LL_Ar_Clean'
	WHEN EQP_ID LIKE 'BETSE%' AND STEP_NAME LIKE 'ET-BPO-Etching' THEN 'BPO'
	WHEN EQP_ID LIKE 'BETSE%' AND STEP_NAME LIKE 'ET-Trch-RW-AR-Sampling' THEN 'Trch-RW-AR'
	WHEN EQP_ID LIKE 'BETSE%' AND STEP_NAME LIKE 'ET-SPA-AR' THEN 'SPA-CLEAN'
	WHEN EQP_ID LIKE 'BETSE%' AND STEP_NAME LIKE 'ET-OQC-REA-AR' THEN 'OQC-REA-AR'	
    END DEVICE_ID
	FROM CIMDM.DM_MOVE_BT WHERE EQP_ID LIKE 'BETSE%'
	AND TRACK_OUT_BT BETWEEN TO_DATE(to_char(sysdate-1,'yyyy-mm-dd') || ' 07:30:00','yyy-mm-dd hh24:24:mi:ss')
	AND TO_DATE(to_char(sysdate,'yyyy-mm-dd') || ' 07:30:00','yyy-mm-dd hh24:24:mi:ss')
),
WPH_SUM_TOTAL AS (
	SELECT SUM(WFR_QTY) WFR_QTY FROM WPH_LIST
),
WPH_SUM AS (
	SELECT SUM(WFR_QTY) WFR_QTY,DEVICE_ID FROM WPH_LIST GROUP BY DEVICE_ID
),
WPH_TABLE AS (
	SELECT DEVICE_ID,CASE 
	WHEN DEVICE_ID='OO' THEN 4.52
	WHEN DEVICE_ID='ViaE' THEN 9.57
	WHEN DEVICE_ID='BPO' THEN 11.85
	WHEN DEVICE_ID='LL_Ar_Clean' THEN 30.14
	WHEN DEVICE_ID='SPA-CLEAN' THEN 30.14
	WHEN DEVICE_ID='OQC-REA-AR' THEN 30.14
	WHEN DEVICE_ID='Trch-RW-AR' THEN 30.14
	WHEN DEVICE_ID='MD' THEN 30
	END WPHTABLE FROM WPH_TABLE
),
WPH_TABLE_STD AS (
	SELECT MAX(WPHTABLE) MAX_STD FROM WPH_TABLE
),
WPH_TABLE2 AS (
	SELECT A.DEVICE_ID,B.MAX_STD/A.WPHTABLE WPHTABLE FROM WPH_TABLE A , WPH_TABLE_STD B
),
WPH_CALCULATE_F AS (
	SELECT A.DEVICE_ID,A.WFR_QTY*B.WPHTABLE R_RESULT FROM WPH_SUM A JOIN WPH_TABLE2 B ON A.DEVICE_ID=B.DEVICE_ID
),
WPH_CALCULATE_B AS (
	SELECT SUM(R_ESULT) R_ESULT FROM WPH_CALCULATE_F
),
UP_LIST AS (
	SELECT ROUND(AVG(UP),4) UP FROM CIMDM.RPT_KER_SUM WHERE (EQP_ID LIKE 'BETSE%' AND FAB='FAB2')
	AND WIPDATE = TO_DATE(SYSDATE-1,'yyyy-mm-dd')
),
AVL_LIST AS (
	SELECT ROUND(AVG(UP+LOST),4) UP FROM CIMDM.RPT_KER_SUM WHERE (EQP_ID LIKE 'BETSE%' AND FAB='FAB2')
	AND WIPDATE = TO_DATE(SYSDATE-1,'yyyy-mm-dd')
)
SELECT ROUND(A.R_ESULT/((B.UP/100)*C.MAX_STD*3*24),4) EFF , ROUND(A.R_ESULT,2) TTL_TOTAL ,C.MAX_STD,D.WFR_QTY E1_MAIN_MOVE,
((B.UP/100)*C.MAX_STD*3*24) MOVE_TARGET,B.UP,E.UP FROM
WPH_CALCULATE_B A,UP_LIST B,WPH_TABLE_STD C,WPH_SUM_TOTAL D,AVL_LIST E

---------------------------NEO TRCH 現在------------------------------------------------


WITH WPH_LIST AS (
	SELECT WFR_QTY,
	CASE
	WHEN EQP_ID LIKE 'BETSE%' AND LOT_TYPE='MD' THEN 'MD'
	WHEN EQP_ID LIKE 'BETSE%' AND STEP_NAME LIKE 'ET-OO-Etching' THEN 'OO'
	WHEN EQP_ID LIKE 'BETSE%' AND STEP_NAME LIKE 'ET-ViaE-Oxide_Etch-ME' THEN 'ViaE'
	WHEN EQP_ID LIKE 'BETSE%' AND STEP_NAME LIKE 'ET-LL-Ar_Clean' THEN 'LL_Ar_Clean'
	WHEN EQP_ID LIKE 'BETSE%' AND STEP_NAME LIKE 'ET-BPO-Etching' THEN 'BPO'
	WHEN EQP_ID LIKE 'BETSE%' AND STEP_NAME LIKE 'ET-Trch-RW-AR-Sampling' THEN 'Trch-RW-AR'
	WHEN EQP_ID LIKE 'BETSE%' AND STEP_NAME LIKE 'ET-SPA-AR' THEN 'SPA-CLEAN'
	WHEN EQP_ID LIKE 'BETSE%' AND STEP_NAME LIKE 'ET-OQC-REA-AR' THEN 'OQC-REA-AR'	
    END DEVICE_ID
	FROM CIMDM.DM_MOVE_BT WHERE EQP_ID LIKE 'BETSE%'
	AND TRACK_OUT_BT BETWEEN TO_DATE(to_char(sysdate,'yyyy-mm-dd') || ' 07:30:00','yyy-mm-dd hh24:24:mi:ss')
	AND TO_DATE(to_char(sysdate+1,'yyyy-mm-dd') || ' 07:30:00','yyy-mm-dd hh24:24:mi:ss')
),
WPH_SUM_TOTAL AS (
	SELECT SUM(WFR_QTY) WFR_QTY FROM WPH_LIST
),
WPH_SUM AS (
	SELECT SUM(WFR_QTY) WFR_QTY,DEVICE_ID FROM WPH_LIST GROUP BY DEVICE_ID
),
WPH_TABLE AS (
	SELECT DEVICE_ID,CASE 
	WHEN DEVICE_ID='OO' THEN 4.52
	WHEN DEVICE_ID='ViaE' THEN 9.57
	WHEN DEVICE_ID='BPO' THEN 11.85
	WHEN DEVICE_ID='LL_Ar_Clean' THEN 30.14
	WHEN DEVICE_ID='SPA-CLEAN' THEN 30.14
	WHEN DEVICE_ID='OQC-REA-AR' THEN 30.14
	WHEN DEVICE_ID='Trch-RW-AR' THEN 30.14
	WHEN DEVICE_ID='MD' THEN 30
	END WPHTABLE FROM WPH_TABLE
),
WPH_TABLE_STD AS (
	SELECT MAX(WPHTABLE) MAX_STD FROM WPH_TABLE
),
WPH_TABLE2 AS (
	SELECT A.DEVICE_ID,B.MAX_STD/A.WPHTABLE WPHTABLE FROM WPH_TABLE A , WPH_TABLE_STD B
),
WPH_CALCULATE_F AS (
	SELECT A.DEVICE_ID,A.WFR_QTY*B.WPHTABLE R_RESULT FROM WPH_SUM A JOIN WPH_TABLE2 B ON A.DEVICE_ID=B.DEVICE_ID
),
WPH_CALCULATE_B AS (
	SELECT SUM(R_ESULT) R_ESULT FROM WPH_CALCULATE_F
),
UP_LIST AS (
	SELECT ROUND(AVG(UP),4) UP FROM CIMDM.RPT_KER_SUM WHERE (EQP_ID LIKE 'BETSE%' AND FAB='FAB2')
	AND WIPDATE = TO_DATE(SYSDATE,'yyyy-mm-dd')
),
AVL_LIST AS (
	SELECT ROUND(AVG(UP+LOST),4) UP FROM CIMDM.RPT_KER_SUM WHERE (EQP_ID LIKE 'BETSE%' AND FAB='FAB2')
	AND WIPDATE = TO_DATE(SYSDATE,'yyyy-mm-dd')
)
SELECT ROUND(A.R_ESULT/((B.UP/100)*C.MAX_STD*3*ROUND((SYSDATE - TO_DATE(TO_CHAR(SYSDATE, 'YYYY-MM-DD') || ' 07:30:00', 'YYYY-MM-DD HH24:MI:SS')) * 24, 4)),4) EFF , ROUND(A.R_ESULT,2) TTL_TOTAL ,C.MAX_STD,D.WFR_QTY E1_MAIN_MOVE,
((B.UP/100)*C.MAX_STD*3*ROUND((SYSDATE - TO_DATE(TO_CHAR(SYSDATE, 'YYYY-MM-DD') || ' 07:30:00', 'YYYY-MM-DD HH24:MI:SS')) * 24, 4)) MOVE_TARGET,
B.UP,E.UP FROM
WPH_CALCULATE_B A,UP_LIST B,WPH_TABLE_STD C,WPH_SUM_TOTAL D,AVL_LIST E