WITH StatusWithNext AS (
    SELECT 
        toolName,
        LOT_STATUS,
        CUR_STATE_DT,
        LEAD(CUR_STATE_DT) OVER (PARTITION BY toolName ORDER BY CUR_STATE_DT) AS NEXT_STATE_DT
    FROM DBO.tool_status
)
SELECT 
    toolName,
    LOT_STATUS,
    CUR_STATE_DT AS PRE_STATE_END_DT,
    COALESCE(NEXT_STATE_DT, CURRENT_TIMESTAMP) AS CUR_STATE_DT
FROM StatusWithNext
ORDER BY CUR_STATE_DT;
