-- INIT database
CREATE TABLE RPT_KER_EQPSTATUS_BT (
  EQP_ID VARCHAR2(100),
  CUR_STATE VARCHAR2(100),
  CUR_STATE_DT Date
 );

INSERT INTO RPT_KER_EQPSTATUS_BT(EQP_ID, CUR_STATE,CUR_STATE_DT) VALUES ('BETDA001','UP',TO_DATE('2024-07-06 08:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO RPT_KER_EQPSTATUS_BT(EQP_ID, CUR_STATE,CUR_STATE_DT) VALUES ('BETDA001','LOST',TO_DATE('2024-07-06 13:00:00', 'YYYY-MM-DD HH24:MI:SS') );
INSERT INTO RPT_KER_EQPSTATUS_BT(EQP_ID, CUR_STATE,CUR_STATE_DT) VALUES ('BETDA001','UP',TO_DATE('2024-07-06 15:00:00', 'YYYY-MM-DD HH24:MI:SS') );

-- QUERY database
WITH StatusWithFirst AS 
( 
SELECT EQP_ID ,CUR_STATE ,CUR_STATE_DT, LEAD(CUR_STATE_DT) OVER (PARTITION BY EQP_ID ORDER BY CUR_STATE_DT) AS NEXT_STATE_DT FROM RPT_KER_EQPSTATUS_BT   WHERE CUR_STATE_DT BETWEEN to_date('2024-07-06 07:30:00', 'yyyy-mm-dd hh24:mi:ss') and to_date('2024-07-07 07:30:00', 'yyyy-mm-dd hh24:mi:ss') AND EQP_ID= 'BETDA001'
),
StatusWithSecond AS ( 
SELECT EQP_ID,CUR_STATE,CUR_STATE_DT AS PRE_STATE_END_DT,COALESCE(NEXT_STATE_DT, CURRENT_DATE) AS CUR_STATE_DT FROM StatusWithFirst ORDER BY PRE_STATE_END_DT  ), 
StatusWithThird AS ( 
SELECT EQP_ID,CUR_STATE ,PRE_STATE_END_DT,CUR_STATE_DT,ROUND((CUR_STATE_DT-PRE_STATE_END_DT)*24,2) AS DURATION  FROM StatusWithSecond
) 
SELECT * FROM (SELECT CUR_STATE, DURATION  FROM StatusWithThird ) PIVOT (SUM(DURATION) FOR CUR_STATE IN ('UP', 'DOWN','BKUP','LOST','TEST_ENG','TEST_CW','MON_DWN','MON_PM','MON_ROU','HOLD_ENG','HOLD_MF','WAIT_EN','WAIT_MF','WAIT_EE','WAIT_PE','FAC'));
