WITH WPH_LIST AS (
	SELECT WFR_QTY,CASE WHEN DEVICE_ID LIKE 'PS5280%' THEN '5280' ELSE 'CIS' END AS DEVICE_ID FROM CIMDM.DM_MOVE_BT 
	WHERE STEP_NAME='ET-E2-Si_Etch' AND TRACK_IN_DT BETWEEN to_date('2024-07-28 07:30:00','yyyy-mm-dd hh24:mi:ss')
	AND to_date('2024-07-29 07:30:00','yyyy-mm-dd hh24:mi:ss')
),
WPH_SUM AS (
   SELECT SUM(WFR_QTY) AS WFR_QTY,DEVICE_ID FROM WPH_LIST GROUP BY DEVICE_ID
),
WPH_TABLE AS (
	SELECT CASE WHEN DEVICE_ID = 'CIS' THEN 4 ELSE 2.2 END AS WPHTABLE  FROM  WPH_SUM
),
WPH_TABLE2 AS(
	SELECT DEVICE_ID,WPHTABLE / Max(WPHTABLE) OVER () AS WPHTABLE FROM WPH_TABLE
),
WPH_CALCULATE AS (
	SELECT A.DEVICE_ID,A.WFR_QTY * B.WPHTABLE AS R_ESULT FROM WPH_SUM A JOIN WPH_TABLE2 B ON A.DEVICE_ID = B.DEVICE_ID;
),
UP_LIST AS (
	SELECT AVG(UP) AS UP FROM CIMDM.RPT_KER_SUM WHERE WIPDATE BETWEEN to_date('2024-07-28 07:30:00','yyyy-mm-dd hh24:mi:ss')
	AND to_date('2024-07-29 07:30:00','yyyy-mm-dd hh24:mi:ss') AND EQP_ID IN ('BETET031-A','BETET031-B')
)


WITH WPH_LIST AS ( 
	SELECT WFR_QTY,CASE WHEN DEVICE_ID LIKE 'PS5280%' THEN 'PS5280' ELSE 'CIS' END AS DEVICE_ID 
	FROM CIMDM.DM_MOVE_BT WHERE STEP_NAME='ET-E2-Si_Etch' AND 
	TRACK_IN_DT BETWEEN 
	to_date('2024-07-28 07:30:00', 'yyyy-mm-dd hh24:mi:ss') and 
	to_date('2024-07-29 07:30:00', 'yyyy-mm-dd hh24:mi:ss')
	),
WPH_SUM AS ( 
	SELECT SUM(WFR_QTY) AS WFR_QTY,DEVICE_ID FROM WPH_LIST GROUP BY DEVICE_ID 
	), 
WPH_TABLE AS ( 
	SELECT CASE WHEN DEVICE_ID = 'PS5280' THEN 2.2 ELSE 4.4 END AS WPHTABLE  FROM  WPH_SUM
	), 
WPH_TABLE2 AS( 
	SELECT DEVICE_ID,WPHTABLE / Max(WPHTABLE) OVER () AS WPHTABLE FROM WPH_TABLE 
), 
WPH_CALCULATE AS (
	SELECT A.DEVICE_ID,A.WFR_QTY * B.WPHTABLE AS R_ESULT FROM WPH_SUM A JOIN WPH_TABLE2 B 
	ON A.DEVICE_ID = B.DEVICE_ID;
), 
UP_LIST AS (
SELECT AVG(UP) AS UP FROM CIMDM.RPT_KER_SUM WHERE EQP_ID IN ('BETET031-A','BETET031-B') AND  
WIPDATE BETWEEN 
to_date('2024-07-28 07:30:00', 'yyyy-mm-dd hh24:mi:ss') and 
to_date('2024-07-29 07:30:00', 'yyyy-mm-dd hh24:mi:ss'))
SELECT SUM(A.R_ESULT)/(B.UP*C.Max(WPHTABLE)*8*24) AS EFF,B.UP AS UP FROM Table_A A,UP_LIST B,WPH_TABLE C;

